server:
  port: 8010

spring:
  datasource:
    driver-class-name: org.h2.Driver
    jdbc-url: jdbc:h2:mem:test;
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2
  jpa:
    properties:
      hibernate:
        jdbc:
          batch_size: 5
    show-sql: true
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop
      jdbc:
        batch-size: 2